name: Build 3DS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer devkitPro
        uses: devkitpro/devkitpro-pacman-action@v1
        with:
          packages: 3ds-dev

      - name: Compiler
        run: make

      - name: Sauvegarder le fichier 3DSX
        uses: actions/upload-artifact@v4
        with:
          name: LuK-Driver-Academy-3DS
          path: |
            *.3dsx
            *.cia
            *.3ds
